---
platform: linux
image_resource:
  type: docker-image
  source: {repository: cunnie/fedora-ruby-bind-utils}

inputs:
- name: sslip.io

run:
  path: sslip.io/ci/tasks/check-dns.sh

params:
  DOMAIN: ""
