# DON'T USE THIS!
#
# NodePorts aren't the right solution; this is for personal testing
# kubectl create -f nodeport-service.yml
# dig -p 32767 127.0.0.1.sslip.io @172.17.0.2
apiVersion: v1
kind: Service
metadata:
  name: sslip-io-pdns-nodeport-service # must be DNS-compliant
spec:
  type: NodePort
  ports:
  - protocol: UDP
    name: dns-udp
    port: 53
    # targetPort: 53
    nodePort: 32767
  selector:
    app: sslip.io-pdns
