apiVersion: apps/v1
kind: Deployment
metadata:
  name: sslip.io-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sslip.io-nginx
  template:
    metadata:
      name: sslip.io-nginx-pod
      labels:
        app: sslip.io-nginx
    spec:
      containers:
      - name: sslip-nginx-container
        image: cunnie/sslip.io-nginx
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
