# fly -t nono sp -p simple -c pipeline-simple.yml
# fly -t nono expose-pipeline -p simple
# fly -t nono unpause-pipeline -p simple
jobs:
- name: unit
  plan:
  - get: src
    trigger: true
  - task: unit
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: fedora
      run:
        path: "true"

- name: integration
  plan:
  - get: src
    trigger: true
    passed: [unit]
  - task: integration
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: fedora
      run:
        path: "false"

resources:
- name: src
  type: git
  icon: github
  source:
    uri: https://github.com/cunnie/sslip.io
