# pipeline for Concourse CI for sslip.io
#
# fly -t nono sp -p sslip.io -c pipeline-sslip.io.yml
# fly -t nono expose-pipeline -p sslip.io
# fly -t nono unpause-pipeline -p sslip.io
jobs:
- name: unit
  public: true
  plan:
  - get: sslip.io
    trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: cunnie/fedora-golang-bosh
      inputs:
      - name: sslip.io
      run:
        dir: sslip.io/src/sslip.io-dns-server
        path: ginkgo
        args:
        - -r
        - .
- name: dns-servers
  public: true
  plan:
  - {get: sslip.io,   trigger: true}
  - {get: every-six-hours,         trigger: true}
  - task: check-dns
    file: sslip.io/ci/tasks/check-dns.yml
    attempts: 2
    params:
      DOMAIN: sslip.io

resources:
- name: sslip.io
  type: git
  icon: github
  source:
    uri: https://github.com/cunnie/sslip.io

- name: every-six-hours
  type: time
  icon: clock
  source: {interval: 6h}
