# pipeline for Concourse CI for sslip.io
#
# fly -t nono sp -p sslip.io -c pipeline-sslip.io.yml
# fly -t nono expose-pipeline -p sslip.io
# fly -t nono unpause-pipeline -p sslip.io
groups:
- name: sslip.io
  jobs:
  - check-dns
  - unit

jobs:
- name: unit
  public: true
  plan:
  - {get: cunnie-bin,   trigger: true}
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: fedora
      inputs:
      - name: cunnie-bin
      run:
        dir: cunnie-bin
        path: ./pdns_pipe_spec.sh
- name: check-dns
  public: true
  plan:
  - {get: sslip.io,   trigger: true}
  - {get: 6h,         trigger: true}
  - task: check-dns
    file: sslip.io/ci/tasks/check-dns.yml
    attempts: 10
    params:
      DOMAIN: sslip.io

resources:
- name: sslip.io
  type: git
  source:
    uri: https://github.com/cunnie/sslip.io
    branch: master
- name: cunnie-bin
  type: git
  source:
    uri: https://github.com/cunnie/bin
    branch: master

- name: 6h
  type: time
  source: {interval: 6h}
