# pipeline for Concourse CI for sslip.io
# fly -t nono sp -p sslip.io -c pipeline-sslip.io.yml
# fly -t nono expose-pipeline -p sslip.io
groups:
- name: sslip.io
  jobs:
  - check-dns

jobs:
- name: check-dns
  public: true
  plan:
  - {get: sslip.io,   trigger: true}
  - {get: 6h,         trigger: true}
  - task: check-dns
    file: sslip.io/ci/tasks/check-dns.yml
    params:
      DOMAIN: sslip.io

resources:
- name: sslip.io
  type: git
  source:
    uri: https://github.com/cunnie/sslip.io
    branch: master

- name: 6h
  type: time
  source: {interval: 6h}
