name: CI Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    # Only run on main repo, not forks
    if: github.repository == 'cunnie/sslip.io'
    runs-on: self-hosted
    container: cunnie/fedora-golang-bosh
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: go mod download && go install github.com/onsi/ginkgo/v2/ginkgo && ginkgo -r -p .
