name: Build cunnie/fedora-golang-bosh

on:
  push:
    paths:
      - "Docker/fedora-golang-bosh/Dockerfile"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    container:
      image: docker:24.0-dind
      options: --privileged
    services:
      docker:
        image: docker:24.0-dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: cunnie
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: Docker/fedora-golang-bosh
          platforms: linux/amd64,linux/arm64
          push: true
          tags: cunnie/fedora-golang-bosh:latest
